[tool.poetry]
name = "starknet-dss"
version = "0.0.1"
description = "MCD on Starknet"
authors = ["MakerDAO"]

[tool.poetry.dependencies]
python = "3.9.0"
pytest = "7.1.2"
pytest-asyncio = "0.19.0"
cairo-lang = "0.10.0"
cairo-nile = "0.9.0"
pytest-xdist = "2.5.0"
pytest-order = "1.0.1"
python-dotenv = "0.20.0"
web3 = "5.30.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = {version = "^21.9b0", allow-prereleases = true}
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
